stages:
  - dockerize
  - deploy

variables:
  IMAGE_NAME: joshuamumo/caimax_client
  IMAGE_TAG: latest
  EC2_HOST: "YOUR_EC2_PUBLIC_IP"
  DOCKER_HUB_USERNAME: "joshuamumo"

default:
  tags:
    - caimax-production

build_and_push_docker_image:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST bash << 'EOF'
        echo "Logging into Docker"
        echo "$DOCKER_HUB_TOKEN" | docker login -u "joshuamumo" --password-stdin
        docker stop caimax_client || true
        docker rm caimax_client || true
        docker image prune -f
        printenv | grep -E 'GOOGLE_|NEXT_|DATABASE_|MAPBOX_|AWS_|RESEND_|AGENT_|SEND_' > .env
        docker pull $IMAGE_NAME:$IMAGE_TAG
        docker run -d --env-file .env --name caimax_client -p 80:3000 --restart unless-stopped $IMAGE_NAME:$IMAGE_TAG
      EOF
  only:
    - main
