export const keywords = [
    "caimax",
    "Caimax",
    "CAIMAX",
    "Judith",
    "Judith Mbiyu",
    "Caimax Properties",
    "properties", "real estate",
    "CAIMAX PROPERTIES",
    "Caimax Properties",
    "homes",
    "luxury homes",
    "luxury",
    "real estate listings",
    "property for sale",
    "property for rent",
    "real estate agency",
    "buy home",
    "sell home",
    "rent home",
    "real estate investment",
    "property management",
    "commercial real estate",
    "residential real estate",
    "real estate broker",
    "real estate agent",
    "house listings",
    "apartment listings",
    "condo listings",
    "townhouse listings",
    "vacation homes",
    "investment properties",
    "property search",
    "home search",
    "real estate market",
    "property listings",
    "real estate services",
    "home buying",
    "home selling",
    "property valuation",
    "real estate consulting",
    "property development",
    "real estate trends",
    "property news",
    "real estate news",
    "property advice",
    "real estate advice",
    "home improvement",
    "property investment",
    "real estate tips",
    "property tips"
]